### ISSUE TITLE
anaconda remove issues.

### ISSUE THREAD

**Issue by flamingbear** [Anaconda-Server/support#14]
Trying to work around my other issues: #13 & #11 I thought I would just use anaconda remove before trying to upload a new pacakge.  It appears to give me an error the first time I try and then succeed after that when using the --force flag.

Try to remove the linux version.
```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
[ServerError] ('Internal server error', 500)
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
```

Try to remove the osx version:
```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
[ServerError] ('Internal server error', 500)
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$
```

If I don't use the --force flag I get different errors:

```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2
Using anaconda-server api site https://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/opt/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 82, in main
    description=__doc__, version=version)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
    return args.main(args)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/commands/remove.py", line 25, in main
    if args.force or bool_input(msg, False):
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/utils/__init__.py", line 323, in bool_input
    inpt = input('%s %s: ' % (prompt, default_str))
AttributeError: 'ColorStream' object has no attribute 'errors'
```

**Comment by flamingbear** [comment]
I actually think it might have succeeded in deleting the package but still returned a 500 server error... FWIW.

**Comment by flamingbear** [comment]
reposting to correct repo  https://github.com/Anaconda-Server/anaconda-client/issues/265
