### ISSUE TITLE
Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages (401 Client Error: UNAUTHORIZED)

### ISSUE THREAD

**Issue by megies** [Anaconda-Server/support#23]
I'm trying to access our channel (at https://anaconda.org/obspy/obspy) and am violently failing to do so from one of my computers (others work fine):
```
vesuv:~$ conda install -c obspy obspy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/linux-64/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/linux-64/repodata.json.bz2).Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2).........
```

What I already did:
 * update `anaconda-client` to most recent version
 * remove all access tokens on site https://anaconda.org/megies/settings/access (https://github.com/Anaconda-Server/docs.anaconda.org/issues/47#issuecomment-62812598)
 * remove local binstar tokens (from `~/.config/binstar`)
 * remove all anaconda installations completely and reinstall from current installer (linux 64bit)

The only thing I can think of is that at some point I might have built conda packages on that computer and uploaded to the old binstar site via some login/token mechanism at some point. But as pointed out before I tried hard to remove any traces of previous logins/tokens/etc.

I'm out of ideas, any hints what could cause this problem (again, it's specific for one of my computers /IPs)?

**Comment by megies** [comment]
Here's some screenshots from when I still tried to fix my whole existing anaconda install (i.e. before removing everything and installing again from scratch -- which didn't help):

![screenshot from 2016-03-01 12 17 08](https://cloud.githubusercontent.com/assets/1842780/13426953/3cc2d080-dfb1-11e5-927f-17d25f014be1.png)
![screenshot from 2016-03-01 12 20 39](https://cloud.githubusercontent.com/assets/1842780/13426961/43251bd6-dfb1-11e5-8adb-6bb2bdf0c2f8.png)

**Comment by dsludwig** [comment]
Hi @megies, I have tried to diagnose this, but I can't seem to get any further without more information. Can you try running these commands:

* `anaconda --verbose whoami`
* `conda --debug install -c obspy obspy`

This will generate some debugging output that may help in diagnosing the issue.

**Comment by megies** [comment]
```
vesuv:~$ anaconda --verbose whoami
[DEBUG] (u'This domain requires token authentication', 401)
Anonymous User
```
```
vesuv:~$ conda --debug install -c obspy obspy
Using Anaconda Cloud api site https://api.anaconda.org
DEBUG:conda.fetch:channel_urls=(u'https://conda.anaconda.org/obspy/linux-64/', u'https://conda.anaconda.org/obspy/noarch/', u'https://conda.anaconda.org/obspy/linux-64/', u'https://conda.anaconda.org/obspy/noarch/', 'https://repo.continuum.io/pkgs/free/linux-64/', 'https://repo.continuum.io/pkgs/free/noarch/', 'https://repo.continuum.io/pkgs/pro/linux-64/', 'https://repo.continuum.io/pkgs/pro/noarch/')
Fetching package metadata: INFO:stdoutlog:Fetching package metadata: 
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): repo.continuum.io
DEBUG:requests.packages.urllib3.connectionpool:"GET /obspy/noarch/repodata.json.bz2 HTTP/1.1" 401 13
Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)INFO:stderrlog:Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)
DEBUG:requests.packages.urllib3.connectionpool:"GET /obspy/linux-64/repodata.json.bz2 HTTP/1.1" 401 13
Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/linux-64/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/linux-64/repodata.json.bz2)INFO:stderrlog:Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/linux-64/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/linux-64/repodata.json.bz2)

[... last line repeated hundreds of times]

Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)INFO:stderrlog:Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)
DEBUG:requests.packages.urllib3.connectionpool:"GET /obspy/noarch/repodata.json.bz2 HTTP/1.1" 401 13
Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)INFO:stderrlog:Warning: you may need to login to anaconda.org again with 'anaconda login' to access private packages(https://conda.anaconda.org/obspy/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/obspy/noarch/repodata.json.bz2)
DEBUG:requests.packages.urllib3.connectionpool:"GET /obspy/noarch/repodata.json.bz2 HTTP/1.1" 401 13
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/megies/anaconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 240, in install
    prefix=prefix)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/api.py", line 43, in get_index
    unknown=unknown)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/megies/anaconda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result
    return self.__get_result()
  File "/home/megies/anaconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata

[... repeat last two Traceback items hundreds of times]

  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    return self.build_response(request, resp)
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 215, in build_response
    response = Response()
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/models.py", line 550, in __init__
    self.headers = CaseInsensitiveDict()
  File "/home/megies/anaconda2/lib/python2.7/site-packages/requests/structures.py", line 46, in __init__
    self.update(data, **kwargs)
  File "/home/megies/anaconda2/lib/python2.7/_abcoll.py", line 564, in update
    if isinstance(other, Mapping):
  File "/home/megies/anaconda2/lib/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
  File "/home/megies/anaconda2/lib/python2.7/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RuntimeError: maximum recursion depth exceeded
```
conda info output:
```
vesuv:~$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 3.19.3
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/megies/anaconda2  (writable)
  default environment : /home/megies/anaconda2
     envs directories : /home/megies/anaconda2/envs
        package cache : /home/megies/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/obspy/linux-64/
                        https://conda.anaconda.org/obspy/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/megies/.condarc
    is foreign system : False
```
cat .condarc:
```
vesuv:~$ cat .condarc
channels:
  - obspy
  - defaults
```

**Comment by dsludwig** [comment]
Thanks @megies! Is it possible you have a `~/.netrc` file present? I saw a similar error (infinite recursion, failing 401) when I set one up.

**Comment by megies** [comment]
Oh my god, what a catch! Nail on head, thanks @dsludwig.

This long-unused `.netrc` file had a `default login` line with password specified, and this is where things went wrong (tried w/ and w/o this default login line).

I find the idea rather strange that conda would..
 - pick up a default login from a file that is according to it's man page used for ftp interaction
 - use this default login over one explicitly specified by user input

**Comment by dsludwig** [comment]
Great, I'm glad your problem is solved @megies!

The `.netrc` authentication is an obscure (mis)feature of the `requests` library we are using for HTTP. I will file an issue with conda to disable it.

**Comment by megies** [comment]
Thanks again @dsludwig, good to hear it's fixed for everybody in future versions!
